#pragma config(UART_Usage, UART1, uartUserControl, baudRate115200, IOPins, None, None)
#pragma config(Sensor, in1,    rightSensor,    sensorLineFollower)
#pragma config(Sensor, in2,    centerSensor,   sensorLineFollower)
#pragma config(Sensor, in3,    leftCenter,     sensorLineFollower)
#pragma config(Sensor, dgtl8,  sonarSensor,    sensorSONAR_cm)
#pragma config(Motor,  port1,           rightmotor,    tmotorVex393_HBridge, openLoop)
#pragma config(Motor,  port10,          leftmotor,     tmotorVex393_HBridge, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

int bnsSerialRead(const TUARTs uart, char* data, int stringSize, int timeoutMilli);
task main()
{
	char myString[4];
	int count= 0;
	while(1) {
		count = bnsSerialRead(UART1,myString, 4,200);
		if (count > 0) {
					writeDebugStream(myString);
		}
		delay(1000);
	}
}

int bnsSerialRead(const TUARTs uart, char* data, int stringSize, int timeoutMilli)
{
	long startTime = nPgmTime;
	int characterCounter = 0;

	for (int i = 0; i < stringSize; i++)
		data[i] = 0;

	while (nPgmTime - startTime < timeoutMilli && characterCounter < stringSize)
	{
		short d = getChar(uart);

		if (d != -1)
		{
			*data = d;
			startTime = nPgmTime;
			characterCounter++;
			data++;
		}
	}
	return characterCounter;
}
