#pragma config(Sensor, in1,    lineFollowerRIGHT, sensorLineFollower)
#pragma config(Sensor, in2,    lineFollowerCENTER, sensorLineFollower)
#pragma config(Sensor, in8,    lineFollowerLEFT, sensorReflection)
#pragma config(Sensor, dgtl5,  leftBumper,     sensorTouch)
#pragma config(Motor,  port1,           leftMotor,     tmotorVex393_HBridge, openLoop, reversed)
#pragma config(Motor,  port10,          rightMotor,    tmotorVex393_HBridge, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//


//================================================
//=========This part is for on/off button only ===
//================================================
bool motorDisabled = true;
bool bClickInProgress = false;

void processButton()
{
	if (bClickInProgress)
	{
		if (SensorValue[leftBumper])
			bClickInProgress = false;
	}
	else
	{
		if (!SensorValue[leftBumper])
		{
			motorDisabled = !motorDisabled;
			bClickInProgress = true;
		}
	}
}
//================================================
//============End of on/off button================
//================================================




//================================================
//======== Common variables for PID ==============
//================================================
int nErrorValue;
int nLastError;
int nDerivative;

int nAdjustment;
int nLeftMotor;
int nRightMotor;

int nMaxSpeed = 40; //40
int nPFactor =  10; //10
//int nIFactor =   0;
int nDFactor =  45; //45
//================================================
//======== End of variables for PID ==============
//================================================


//================================================
//======== get error for Proportional ============
//================================================


//================================================
//======== End of getting error for Proportional==
//================================================


int getLineErrorPosition()
{
	static int nLastPos = 0;
	int nPos = 0;
	int nNumbOfHits = 0;
	const int kThreshold1 = 158;
	const int kThreshold2 = 1389;
	const int kThreshold3 = 2621;

#define checkSensor(nSensor, nWeight)\
	if (SensorValue[nSensor]  > kThreshold1)\
	{\
		if (SensorValue[nSensor] > kThreshold3)\
		{nPos += 3 * nWeight; nNumbOfHits += 3;}\
		else if (SensorValue[nSensor] > kThreshold2)\
		{nPos += 2 * nWeight; nNumbOfHits += 2;}\
		else \
		{nPos += 1 * nWeight; nNumbOfHits += 1;}\
	}

	checkSensor(lineFollowerLEFT,   +20); //70
	checkSensor(lineFollowerCENTER,   0); //30
	checkSensor(lineFollowerRIGHT,  -20);


	switch (nNumbOfHits)
	{
	case 0:
		// Line was not detected. Use the last detected value
		return nLastPos;

	case 1:
		break;

	default:
		nPos /= nNumbOfHits;
		break;
	}
	nLastPos = nPos;      // Save the last detected position
	return nPos;
}

//================================================
//======== End of get error for Proportional =====
//================================================

task main()
{
	wait1Msec(2000);
	while(true) {
		processButton();
		nErrorValue = getLineErrorPosition();
		nDerivative = nErrorValue - nLastError;
		nAdjustment = ((nErrorValue * nPFactor) + (nDerivative * nDFactor))/ 100;
		nLastError  = nErrorValue;

		if (nAdjustment > 0)
		{
			nLeftMotor  = nMaxSpeed + nAdjustment;
			nRightMotor = nMaxSpeed - 10 * nAdjustment / 2; //8
			if (nRightMotor < 0)
				nRightMotor = 0;
		}
		else
		{
			nLeftMotor  = nMaxSpeed + 10 * nAdjustment / 2;
			nRightMotor = nMaxSpeed - nAdjustment;
			if (nLeftMotor < 0)
				nLeftMotor = 0;
		}

		if (motorDisabled)
		{
			motor[leftMotor]  = 0;
			motor[rightMotor] = 0;
		}
		else
		{
			motor[leftMotor]  = nLeftMotor;
			motor[rightMotor] = nRightMotor;
		}
	}
}
